# Generated by Django 5.2.4 on 2025-07-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inspecao', models.DateField()),
                ('tecnico_responsavel', models.CharField(max_length=100)),
                ('plataforma', models.CharField(choices=[('P-1', 'P-1'), ('P-2', 'P-2'), ('P-3', 'P-3'), ('P-4', 'P-4')], max_length=3)),
                ('modulo', models.CharField(choices=[('M01', 'M01'), ('M02', 'M02'), ('M03', 'M03'), ('M04', 'M04'), ('M05', 'M05'), ('M06', 'M06'), ('M07', 'M07'), ('M08', 'M08'), ('M09', 'M09'), ('M10', 'M10')], max_length=3)),
                ('setor', models.CharField(choices=[('S01', 'S01'), ('S02', 'S02'), ('S03', 'S03')], max_length=3)),
                ('tipo_equipamento', models.CharField(choices=[('Vaso de Pressão', 'Vaso de Pressão'), ('Tanque', 'Tanque'), ('Permutador', 'Permutador'), ('Filtro', 'Filtro')], max_length=20)),
                ('tag', models.CharField(max_length=10)),
                ('defeito', models.CharField(choices=[('Redução de espessura', 'Redução de espessura'), ('Vazamento', 'Vazamento'), ('Trinca', 'Trinca'), ('Desgaste anormal', 'Desgaste anormal'), ('Outro', 'Outro')], max_length=30)),
                ('causa', models.CharField(choices=[('Corrosão externa', 'Corrosão externa'), ('Corrosão interna', 'Corrosão interna'), ('Vibração excessiva', 'Vibração excessiva'), ('Impacto', 'Impacto'), ('Outro', 'Outro')], max_length=30)),
                ('categoria_rti', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=3)),
                ('recomendacao_rti', models.CharField(choices=[('Reparar imediatamente', 'Reparar imediatamente'), ('Estender prazo de execução', 'Estender prazo de execução'), ('Interromper o serviço', 'Interromper o serviço'), ('Pintura', 'Pintura'), ('Outra', 'Outra')], max_length=30)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
            ],
        ),
    ]
